# Generated by Django 5.1.3 on 2024-12-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_alter_movie_background_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='yt_trailer_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
