# Generated by Django 5.1.3 on 2024-12-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_alter_movie_yt_trailer_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='mpa_rating',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='state',
            field=models.CharField(blank=True, default='ok', max_length=255, null=True),
        ),
    ]
