# Generated by Django 5.1.3 on 2024-12-04 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0010_auto_20241204_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genres',
            new_name='genre_json',
        ),
    ]
