# Generated by Django 5.1.3 on 2024-12-04 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0011_rename_genres_movie_genre_json'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genre_r',
            new_name='genres',
        ),
    ]
